// <auto-generated />
using System;
using Dealmatcher.Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dealmatcher.Backend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.ConversationAggregate.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("OfferId");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.ConversationAggregate.Messages.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.PrimitiveCollection<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Offers", (string)null);
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Properties.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("PropertyDefinitionId");

                    b.ToTable("Properties", (string)null);

                    b.HasDiscriminator<string>("PropertyType").HasValue("Property");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.PropertyDefinitions.PropertyDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefinitionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("PropertyDefinitions", (string)null);

                    b.HasDiscriminator<string>("DefinitionType").HasValue("PropertyDefinition");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.UserAggregate.Ban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IssuedById")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssuedById");

                    b.HasIndex("UserId");

                    b.ToTable("Bans", (string)null);
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.UserAggregate.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Properties.BooleanProperty", b =>
                {
                    b.HasBaseType("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Properties.Property");

                    b.Property<bool>("Value")
                        .HasColumnType("bit")
                        .HasColumnName("BooleanValue");

                    b.HasDiscriminator().HasValue("Boolean");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Properties.NumericProperty", b =>
                {
                    b.HasBaseType("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Properties.Property");

                    b.Property<double>("Value")
                        .HasColumnType("float")
                        .HasColumnName("NumericValue");

                    b.HasDiscriminator().HasValue("Numeric");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Properties.SelectProperty", b =>
                {
                    b.HasBaseType("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Properties.Property");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SelectValue");

                    b.HasDiscriminator().HasValue("Select");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Properties.TextProperty", b =>
                {
                    b.HasBaseType("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Properties.Property");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TextValue");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.PropertyDefinitions.BooleanPropertyDefinition", b =>
                {
                    b.HasBaseType("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.PropertyDefinitions.PropertyDefinition");

                    b.HasDiscriminator().HasValue("Boolean");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.PropertyDefinitions.NumericPropertyDefinition", b =>
                {
                    b.HasBaseType("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.PropertyDefinitions.PropertyDefinition");

                    b.HasDiscriminator().HasValue("Numeric");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.PropertyDefinitions.SelectPropertyDefinition", b =>
                {
                    b.HasBaseType("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.PropertyDefinitions.PropertyDefinition");

                    b.Property<string>("_values")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Values");

                    b.HasDiscriminator().HasValue("Select");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.PropertyDefinitions.TextPropertyDefinition", b =>
                {
                    b.HasBaseType("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.PropertyDefinitions.PropertyDefinition");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.UserAggregate.BasicUser", b =>
                {
                    b.HasBaseType("Dealmatcher.Backend.Domain.EntityAggregates.UserAggregate.User");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("BasicUser");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.ConversationAggregate.Conversation", b =>
                {
                    b.HasOne("Dealmatcher.Backend.Domain.EntityAggregates.UserAggregate.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.ConversationAggregate.Messages.Message", b =>
                {
                    b.HasOne("Dealmatcher.Backend.Domain.EntityAggregates.ConversationAggregate.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Dealmatcher.Backend.Domain.EntityAggregates.UserAggregate.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Offer", b =>
                {
                    b.HasOne("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Categories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dealmatcher.Backend.Domain.EntityAggregates.UserAggregate.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Properties.Property", b =>
                {
                    b.HasOne("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Offer", null)
                        .WithMany("Properties")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.PropertyDefinitions.PropertyDefinition", "PropertyDefinition")
                        .WithMany()
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PropertyDefinition");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.PropertyDefinitions.PropertyDefinition", b =>
                {
                    b.HasOne("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Categories.Category", null)
                        .WithMany("PropertyDefinitions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.UserAggregate.Ban", b =>
                {
                    b.HasOne("Dealmatcher.Backend.Domain.EntityAggregates.UserAggregate.User", "IssuedBy")
                        .WithMany()
                        .HasForeignKey("IssuedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Dealmatcher.Backend.Domain.EntityAggregates.UserAggregate.User", "User")
                        .WithMany("Bans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("IssuedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.ConversationAggregate.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Categories.Category", b =>
                {
                    b.Navigation("PropertyDefinitions");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.OfferAggregate.Offer", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Dealmatcher.Backend.Domain.EntityAggregates.UserAggregate.User", b =>
                {
                    b.Navigation("Bans");
                });
#pragma warning restore 612, 618
        }
    }
}
