name: Dealmatcher CD - main

on:
  push:
    branches: 
      [ main ]

jobs:
  backend-build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEALMATCHERBACKENDPROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEALMATCHERBACKENDPROD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEALMATCHERBACKENDPROD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src/backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.DEALMATCHERBACKENDPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEALMATCHERBACKENDPROD_REGISTRY_PASSWORD }}
          containerAppName: dealmatcher-backend-prod
          resourceGroup: rg-dealmatcher
          imageToBuild: xxxdkgxxx/dealmatcher-backend-prod:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_

  frontend-cd-main:
    name: Dealmatcher main frontend CD - main
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./src/frontend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-${{ runner.os }}-${{ hashFiles('src/frontend/pubspec.lock') }}
          restore-keys: |
            pub-${{ runner.os }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('src/frontend/android/**/*.gradle*', 'src/frontend/android/**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Install dependencies
        run: flutter pub get

      - name: Build app
        run: flutter build apk --release -t lib/main_main.dart

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: src/frontend/build/app/outputs/flutter-apk/app-release.apk