name: frontend flutter develop CI

on:
  push:
    branches: [ develop, flutter_ci ]

jobs:
  frontend-dev:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/frontend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Check Dart formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze project
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
